const GAME_SENTENCES = {
    en: [
        "The Amazon Rainforest, often referred to as the lungs of the Earth, produces a significant amount of the world's oxygen. It is home to millions of species of plants and animals, many of which are not found anywhere else. Preserving this ecosystem is crucial for the health of our planet.",
        "Space exploration has always fascinated humanity. From the first steps on the Moon to the rovers exploring Mars, our curiosity drives us to look beyond our own world. Scientists hope that one day we might find evidence of life on other planets or even establish colonies among the stars.",
        "Technology has transformed the way we communicate and access information. With just a few clicks, we can connect with people on the other side of the globe or learn about any topic imaginable. However, it is important to use these tools responsibly and maintain a balance with the physical world.",
        "History teaches us valuable lessons about the rise and fall of civilizations. By studying the past, we can understand the mistakes and achievements of our ancestors. This knowledge helps us make better decisions for the future and appreciate the diverse cultures that shape our world today.",
        "A healthy lifestyle involves more than just eating vegetables and exercising. It also means taking care of our mental well-being, getting enough sleep, and building strong relationships with others. Small daily habits can lead to significant improvements in our overall quality of life.",
        "Artificial intelligence is rapidly changing the landscape of many industries. From healthcare to finance, AI algorithms are being used to analyze vast amounts of data and make predictions. While this technology offers many benefits, it also raises ethical questions about privacy and job displacement.",
        "Climate change is one of the most pressing issues facing our planet today. Rising temperatures, melting ice caps, and extreme weather events are just some of the consequences. It is imperative that we take collective action to reduce our carbon footprint and protect the environment for future generations.",
        "Music has the power to evoke strong emotions and bring people together. Whether it's a classical symphony or a catchy pop song, music transcends language barriers and connects us on a deeper level. Learning to play an instrument can also have cognitive benefits and improve memory.",
        "Reading is a gateway to new worlds and ideas. Through books, we can travel to distant lands, meet fascinating characters, and explore complex themes. Regular reading not only improves vocabulary and comprehension but also stimulates the imagination and empathy.",
        "The ocean covers more than 70% of the Earth's surface and remains largely unexplored. It plays a vital role in regulating the global climate and providing food for billions of people. Protecting marine life and reducing plastic pollution are essential for maintaining the health of our oceans."
    ],
    es: [
        "La selva amazónica, a menudo llamada los pulmones de la Tierra, produce una cantidad significativa del oxígeno del mundo. Es el hogar de millones de especies de plantas y animales, muchos de los cuales no se encuentran en ningún otro lugar. Preservar este ecosistema es crucial para la salud de nuestro planeta.",
        "La exploración espacial siempre ha fascinado a la humanidad. Desde los primeros pasos en la Luna hasta los rovers que exploran Marte, nuestra curiosidad nos impulsa a mirar más allá de nuestro propio mundo. Los científicos esperan que algún día podamos encontrar evidencia de vida en otros planetas.",
        "La tecnología ha transformado la forma en que nos comunicamos y accedemos a la información. Con solo unos pocos clics, podemos conectarnos con personas al otro lado del mundo o aprender sobre cualquier tema imaginable. Sin embargo, es importante usar estas herramientas de manera responsable.",
        "La historia nos enseña lecciones valiosas sobre el auge y la caída de las civilizaciones. Al estudiar el pasado, podemos entender los errores y logros de nuestros antepasados. Este conocimiento nos ayuda a tomar mejores decisiones para el futuro y apreciar las diversas culturas.",
        "Un estilo de vida saludable implica más que solo comer verduras y hacer ejercicio. También significa cuidar nuestro bienestar mental, dormir lo suficiente y construir relaciones sólidas con los demás. Los pequeños hábitos diarios pueden conducir a mejoras significativas en nuestra calidad de vida.",
        "La inteligencia artificial está cambiando rápidamente el panorama de muchas industrias. Desde la atención médica hasta las finanzas, los algoritmos de IA se utilizan para analizar grandes cantidades de datos. Aunque esta tecnología ofrece muchos beneficios, también plantea preguntas éticas sobre la privacidad.",
        "El cambio climático es uno de los problemas más urgentes que enfrenta nuestro planeta hoy en día. El aumento de las temperaturas y los fenómenos meteorológicos extremos son algunas de las consecuencias. Es imperativo que tomemos medidas colectivas para reducir nuestra huella de carbono.",
        "La música tiene el poder de evocar emociones fuertes y unir a las personas. Ya sea una sinfonía clásica o una canción pop pegadiza, la música trasciende las barreras del idioma. Aprender a tocar un instrumento también puede tener beneficios cognitivos y mejorar la memoria.",
        "La lectura es una puerta de entrada a nuevos mundos e ideas. A través de los libros, podemos viajar a tierras lejanas, conocer personajes fascinantes y explorar temas complejos. La lectura regular no solo mejora el vocabulario, sino que también estimula la imaginación y la empatía.",
        "El océano cubre más del 70% de la superficie de la Tierra y permanece en gran parte inexplorado. Juega un papel vital en la regulación del clima global y proporciona alimento a miles de millones de personas. Proteger la vida marina y reducir la contaminación por plástico son esenciales."
    ],
    fr: [
        "La forêt amazonienne, souvent appelée les poumons de la Terre, produit une quantité importante de l'oxygène mondial. Elle abrite des millions d'espèces de plantes et d'animaux, dont beaucoup ne se trouvent nulle part ailleurs. Préserver cet écosystème est crucial pour la santé de notre planète.",
        "L'exploration spatiale a toujours fasciné l'humanité. Des premiers pas sur la Lune aux rovers explorant Mars, notre curiosité nous pousse à regarder au-delà de notre propre monde. Les scientifiques espèrent qu'un jour nous pourrons trouver des preuves de vie sur d'autres planètes.",
        "La technologie a transformé la façon dont nous communiquons et accédons à l'information. En quelques clics, nous pouvons nous connecter avec des personnes à l'autre bout du monde ou apprendre sur n'importe quel sujet. Cependant, il est important d'utiliser ces outils de manière responsable.",
        "L'histoire nous enseigne de précieuses leçons sur l'essor et la chute des civilisations. En étudiant le passé, nous pouvons comprendre les erreurs et les réalisations de nos ancêtres. Ces connaissances nous aident à prendre de meilleures décisions pour l'avenir et à apprécier les diverses cultures.",
        "Un mode de vie sain implique plus que de simplement manger des légumes et faire de l'exercice. Cela signifie également prendre soin de notre bien-être mental, dormir suffisamment et nouer des relations solides avec les autres. De petites habitudes quotidiennes peuvent conduire à des améliorations significatives.",
        "L'intelligence artificielle change rapidement le paysage de nombreuses industries. De la santé à la finance, les algorithmes d'IA sont utilisés pour analyser de grandes quantités de données. Bien que cette technologie offre de nombreux avantages, elle soulève également des questions éthiques.",
        "Le changement climatique est l'un des problèmes les plus urgents auxquels notre planète est confrontée aujourd'hui. La hausse des températures et les événements météorologiques extrêmes en sont quelques conséquences. Il est impératif que nous prenions des mesures collectives pour réduire notre empreinte carbone.",
        "La musique a le pouvoir d'évoquer des émotions fortes et de rassembler les gens. Qu'il s'agisse d'une symphonie classique ou d'une chanson pop entraînante, la musique transcende les barrières linguistiques. Apprendre à jouer d'un instrument peut également avoir des avantages cognitifs.",
        "La lecture est une porte d'entrée vers de nouveaux mondes et de nouvelles idées. À travers les livres, nous pouvons voyager vers des terres lointaines, rencontrer des personnages fascinants et explorer des thèmes complexes. La lecture régulière améliore non seulement le vocabulaire mais stimule aussi l'imagination.",
        "L'océan couvre plus de 70% de la surface de la Terre et reste largement inexploré. Il joue un rôle vital dans la régulation du climat mondial et fournit de la nourriture à des milliards de personnes. Protéger la vie marine et réduire la pollution plastique sont essentiels pour nos océans."
    ]
};
